version: "3"
services:
  # Create frontend container
  frontend: # Name of our service
    image: s0517019/new-year-bingo-game-frontend # Your docker image
    ports: # Port binding to host from docker container
      - "80:8080" # Bind port 8080 of host to 8080 of container
    container_name: new-year-bingo-game-frontend-container
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    image: s0517019/new-year-bingo-game-backend # Your docker image
    ports:
      - "3000:3000" # Bind port 3000 of host to 3000 of container
      - "4000:4000" # Bind port 4000 of host to 4000 of container
    container_name: new-year-bingo-game-backend-container
    restart: always
    environment:
      MONGO_URI: mongodb+srv://haruki:test@cluster0.dqivi.mongodb.net/?retryWrites=true&w=majority
