version: "3"
services:
  # Create frontend container
  frontend:
    image: s0517019/new-year-bingo-game-frontend # Your docker image
    ports:
      - "80:8080" 
    container_name: frontend
    restart: always 
    networks:
      - mynetwork
    depends_on:
      - backend

  # Create backend container
  backend:
    image: s0517019/new-year-bingo-game-backend # Your docker image
    ports:
      - "3000:3000"
      - "4000:4000"
    container_name: backend
    restart: always
    environment:
      MONGO_URI: "{{ MONGO_URI }}"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
