name: Build

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Back-end
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: s0517019/new-year-bingo-game-backend:latest

      - name: Build and push Front-end
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: s0517019/new-year-bingo-game-frontend:latest
